### ISSUE TITLE
Pull in SAF community work outside of InSpec profiles/Heimdall

### ISSUE THREAD

**Issue by wdower** [CMSgov/saf#10]
CMS SAF mostly focused on InSpec and Heimdall at the moment -- we can include content from (or at least links to) other CMS work in secure automation.

Need content for:
- Cloud efforts
- Encryption efforts
- Teams which already implement DevOps at CMS

Idea is to weave SAF through existing community work at CMS.

**Comment by wdower** [comment]
Need a table of:

 | teams | what they do | any links |

For all the SAF community. This can live on its own page.

**Comment by ejaronne** [comment]
From "ACT Support" and "DevOps Pilots and Onboarding" tiles on home, link to this page:

Page titled: "ACT Support, DevOps Pilots and Onboarding"

Team | Scope |
ACT |  Uses security testing data and Heimdall from this framework to support Assessments
IUSG |  Incorporates tools from this framework into their CMS DevSecOps guidance
BCDA |  Uses the AWS CIS Foundations and Red Hat InSpec profiles and Heimdall in their DevOps pipeline
CFACTS |  Uses these InSpec profiles and Heimdall to routinely assess and remediate their supporting operating systems, databases, web servers, and COTS software
T-MSIS |  Uses Red Hat InSpec profiles and Heimdall in their DevOps pipeline
IDM |  Uses the AWS CIS Foundations and Red Hat InSpec profiles and Heimdall in their DevOps pipeline
MACFin |  Uses the AWS CIS Foundations, Red Hat, CVE, JBoss, Oracle RDS, Heimdall tools in their DevOps pipeline
Lewin Group |  Uses the Red Hat InSpec profile and Ansible hardening to routinely assess and remediate their servers, and support their ACT

**Comment by ejaronne** [comment]
I had preferred the title of the page to be titled: "ACT Support, DevOps Pilots and Onboarding"
