### ISSUE TITLE
Add a Tool Chain Page or add more context/graphics on tools and how they fit together

### ISSUE THREAD

**Issue by wdower** [CMSgov/saf#11]
User feedback suggests it is not immediately clear how all of our tools fit together ("what is Vulcan in relation to InSpec, in relation to Heimdall, in relation to the support tools?"). Current cards are confusing to non-devs.

This can be fixed by:
- describing tool ecosystem better (getting started page (?))
- adding a graphic to show profile development pipeline (homepage (?))

We can utilize existing SAF slide decks for helpful diagrams.

We need a page to describe how all the word soup of MITRE tools fit together.

Needs to show the relationship between Vulcan/InSpec/Heimdall(-Lite?)/the support tools. A simple graphic would be nice (from Eugene when possible).

**Comment by wdower** [comment]
Needs a simple graphic showing the relationship between tools (INSPEC --> HEIMDALL etc.) and a brief blurb on what each one does. This info can live on its own page.

**Comment by ejaronne** [comment]
Place this image on home page below:
"How We Support It
Develop a toolchain to support the above areas of What and How for secure development"
and above the existing tiles. Leave the existing tiles.

![SAF_Tool_Chain_Draft_05142020](https://user-images.githubusercontent.com/34140975/81941979-87f17400-95c7-11ea-8c22-24daac1a1f0a.png)
