### ISSUE TITLE
Add implementation/hardening page

### ISSUE THREAD

**Issue by wdower** [CMSgov/saf#24]

**Comment by ejaronne** [comment]
Replace:
"CMS Official Content
CMS SAF implementation and hardening content will be added to this site as it is developed.
Partner Content
The open-source community has developed basic Ansible, Chef, and Terraform hardening baselines to help securely configure common system components. Our partners at MITRE are providing stewardship over these hardening baselines here. Please note that this content is not designed to align with CMS ARS controls."

with:

"CMS ISPG is helping to provide stewardship over open-source community-based implementation/hardening content to help configure the security of common system components, hosted here and at other community vendor sites. Our partners at MITRE host baseline implementation/hardening content [here](https://saf.mitre.org/#/hardening). Over time, CMS will populate this page with overlays to these implementation baselines, tailored to specific CMS-policy requirements."
