### ISSUE TITLE
FAQ: "Which tools are supported by the CMS SAF?"

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/saf#35]
A: List InSpec, Heimdall, and the tools that Heimdall_tools converts.

**Comment by ejaronne** [comment]
While we're here, I concur that it is time to default to a collapsed mode for the FAQ page, similar to the one at MITRE. The page now has enough items to warrant it.

**Comment by ejaronne** [comment]
Let's try a simple, direct list first, before concerning ourselves with logos (Thanks, but drop the logos for now please):

FAQ: "Which security tools are supported under CMS SAF?"

Answer:
- InSpec (and our InSpec profiles[link]) for assessing configuration settings, vulnerabilities, and least functionality
- Heimdall Lite[link] and Server[link] to visualize security data easily
- Heimdall_tools[link] to convert data from these tools to be viewed in Heimdall:
  - SonarQube
  - Fortify
  - OWASP ZAP
  - Burp Suite Pro
  - Nessus

**Comment by ejaronne** [comment]
- Heimdall Server to visualize security data **_using a full viewer instance to store results, corrdinate across the development team, and more_**
- Heimdall Lite to visualize security data easily from anywhere**_, using a lightweight in-browser version of Heimdall for simple use cases_**
- Heimdall_tools **_[link to heimdall_tools page]_** to convert data from these tools (to Heimdall Data Format - HDF) to be viewed in Heimdall:

**Comment by wdower** [comment]
Fixed
