### ISSUE TITLE
Add Getting Started and FAQ on how InSpec is installed

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/saf#40]
Using some words (ask Eugene) to preface the following image to convey that InSpec may be installed in various ways depending on the need of the user

![image](https://user-images.githubusercontent.com/34140975/84299402-aa22d700-ab1e-11ea-89f6-520d3b3478d7.png)

**Comment by ejaronne** [comment]
Replace placeholder "(Placeholder) One of InSpec's core stengths is its deployment flexibility. InSpec can run tests on a local machine or a remote host, without installing an agent on the target."
with "It is intended and recommended that InSpec be installed on a "runner" host (such as a DevOps orchestration server, an administrative management system, or a developer's workstation/laptop) against the target remotely. However, InSpec may be deployed in various ways depending on the needs of the user:"

**Comment by ejaronne** [comment]
Also, add an FAQ: "How is InSpec deployed?"
A: "It is intended and recommended that InSpec be installed on a "runner" host (such as a DevOps orchestration server, an administrative management system, or a developer's workstation/laptop) and run against the target remotely. However, InSpec may be deployed in various ways depending on the needs of the user:", followed by the same picture.

**Comment by wdower** [comment]
"Target Systems to Assess" ==> "Target Systems to Validate Against the InSpec Profile Content"

**Comment by ejaronne** [comment]
Updated recommended graphic based on last week's feedback:
![image](https://user-images.githubusercontent.com/34140975/85745483-bb99e080-b6d3-11ea-9715-772ab13a64fe.png)
