### ISSUE TITLE
Update all CMS SAF overlay InSpec profiles to latest conventions

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/saf#68]
- [ ] README - model after https://github.com/CMSgov/cms-ars-3.1-moderate-red-hat-enterprise-linux-7-stig-overlay/blob/master/README.md
- [ ] in inspec.yml, set `inspec_version: ">= 4.0"`
- [ ] in inspec.yml, set path to url style
- [ ] in inspec.yml, change from attributes to inputs
- [ ] in inspec.yml, set `profile: ` for any inputs meant to override the baseline settings
- [ ] in inspec.yml, set `sensitive: ` flags as appropriate, e.g., for user names, passwords, hostnames, etc.
- [ ] in controls/, remove any instances of changes to the nist tag, and replace as needed according to the appropriate approach indicated in the lifecycle SOP https://saf.cms.gov/CMS_InSpec_Profile_Lifecycle_SOP_v1.0_20190702.pdf
- [ ] in inspec.yml, validate if any supports statements are valid at the overlay and baseline levels

**Comment by karikarshivani** [comment]
**[Progress Tracker](https://github.com/CMSgov/saf/projects/2)**

**Comment by karikarshivani** [comment]
Phase 1 was completed by following this checklist so I'm closing this issue. Thanks!
