### ISSUE TITLE
Make homepage cards clickable where possible

### ISSUE THREAD

**Issue by wdower** [CMSgov/saf#9]
User feedback says users expect cards on the front page to be clickable and lead to more information about their topic. Need to link to or develop content to be linked to by current cards (where possible -- some cards are WYSIWYG).

Specific examples --

- "Normalizing Security Data" should describe what HDF is on click
- "DevOps Pilots and Onboarding" should link to what the existing pilots are.
- "Training for DevOps" should also link to DevOps training that is not necessarily security-related - more program management stuff like how to build out a DevOps capable team and how to manage them(?)

I'd suggest a mix of linking to other CMS secure automation team information as well as new pages on SAF site to describe, say,

**Comment by wdower** [comment]
Discussion about homepage cards on 4-27:

WHAT WE DO cards:

- Validation --> points to Validation page, DONE
- Visualization --> point to heimdall-lite demo
- Training --> points to CMS SAF training page, DONE
- Open Source Community --> point here https://github.com/orgs/CMSgov/teams/ispg/repositories
- Mature DevSecOps Best Practices --> point to Getting Started page, rename the "What is DevSecOps" section to "Mature DevSecOps" best practices and link some related materials
- Quality Assurance -- did we discuss this one?

HOW WE DO IT cards:

- Standardizing --> point to Validation page
- Normalizing --> point to Heimdall Tools page
- Analyzing --> point to heimdall-lite demo
- Hardening --> point to MITRE SAF hardening page for now. Also rename this card Implementation/Hardening, because the "hardening" page should be renamed to "implementation" in the future

HOW WE SUPPORT IT cards:
- ACT Support -- pull this card because we don't have good content for it
- DSO Pilots -- link to the Open Source Community page we need to develop
- Training -- links to training page, DONE
- Automated Assessment --  pull this card because we don't have good content for it
- Control Status Reporting -- link to heimdall (server) demo

The tools cards are good as they are.

**Comment by ejaronne** [comment]
ACT Support -- (KEEP and point to the same page we point DSO Pilots to)
https://github.com/CMSgov/saf/issues/10#issuecomment-620896383

**Comment by ejaronne** [comment]
RE: Mature DevSecOps Best Practices --> point to Getting Started page, rename the "What is DevSecOps" section to "Mature DevSecOps" best practices and link some related materials, list the 

- DevSecOps Checklist (already there, remove word "Practices")
- DevSecOps Best Practices Guide (attached)
[DRAFT-DevSecOps_Best_Practices_Guide_20190516.pdf](https://github.com/CMSgov/saf/files/4549005/DRAFT-DevSecOps_Best_Practices_Guide_20190516.pdf)
- InSpec Profile Lifecycle SOP https://cmsgov.github.io/saf/CMS_InSpec_Profile_Lifecycle_SOP_v1.0_20190702.pdf
